### ISSUE TITLE
Some tests fail when running from different path

### ISSUE THREAD

**Issue by oritstone** [CloudSlang/cloud-slang-content#113]
Tests for operations:
- copy
- create folder
- move
Are ignored since they fail in Travis
the tests relay on folders from the content repo

**Comment by tudorlesan** [comment]
@orius123 I understand copy and move failing since the tests try to use files from local path which is assumed to be our content. So running tests from different path will not find those particular files.
What I don't get is how can create folder fail, which just creates a folder and deletes it?

Are we sure it fails for the same reason?

**Comment by tudorlesan** [comment]
@oritstone added wrapper flows over copy and move so Travis builds pass. Not sure how to fix testCopyFolderFailureIllegal and testMoveFolderFailureWithDestinationFolderPathInexistent since I tried those actions using SSH and it failed as expected. Don't know how these end with SUCCES in our tests.
 Added wrapper flow for create_folder also
