### ISSUE TITLE
dind-ssh docker image “Driver btrfs failed to create image rootfs” error

### ISSUE THREAD

**Issue by raskin-aleksandr** [CloudSlang/cloud-slang-content#139]
I tries to pull an image working inside dind and got an error `Driver btrfs failed to create image rootfs`
It appears when tried download `ubuntu` or `rastasheep/ubuntu-sshd` docker images

**Comment by meirwah** [comment]
not sure if it is related but i'm getting this error: 
[8] System error: mountpoint for cgroup not found

when i try to run a container

**Comment by orius123** [comment]
Do you use sudo?

**Comment by meirwah** [comment]
I didn't...

**Comment by raskin-aleksandr** [comment]
I did not had problem to pull `hello-world` or `mysql` images

**Comment by orius123** [comment]
Meir's problem looks like sudo issue to me. Don't know about Alex though..

**Comment by orius123** [comment]
Does it happen consistenly?

**Comment by meirwah** [comment]
maybe this has to do:
 BTRFS IS VERY SENSITIVE TO LOW DISK SPACE CONDITIONS. So if you test that code, make sure that you have plenty of disk space. If disk space drops below 1 GB, stop, and enlarge your volume. Otherwise, the Go runtime might crash or freeze (even if there seems to be disk space available). I wasted almost 1 day to debug this issue (I was trying to understand why some tests would randomly fail…), I hope nobody else will hit it :-)

https://blog.docker.com/2013/05/btrfs-support-for-docker/

**Comment by meirwah** [comment]
I tried to run container with sudo, same issue : 
8c2e06607696: Error pulling image (latest) from busybox, Driver btrfs failed to create image rootfs 6ce2e90b0bc7224de3db1f0d646fe8e2c4dd37f1793928287f6074breate btrfs snapshot: file exists ailed to create btrfs snapshot: file exists
FATA[0005] Error pulling image (latest) from busybox, Driver btrfs failed to create image rootfs 6ce2e90b0bc7224de3db1f0d646fe8e2c4dd37f1793928287f6074bc45te btrfs snapshot: file exists

**Comment by meirwah** [comment]
Well i think we fixed this... @raskin-aleksandr @orius123  if you see that as fixed, close this..
