### ISSUE TITLE
Reduce build time

### ISSUE THREAD

**Issue by orius123** [CloudSlang/cloud-slang-content#194]

**Comment by orius123** [comment]
I have split the test to run in parallel test suites and still each node runs in about 10 mins..  Any more suggestion how we get better? anyone?

**Comment by orius123** [comment]
@oritstone @meirwah @Bonczidai @tudorlesan 
:question:

**Comment by Bonczidai** [comment]
1 idea: in the test wrapper flows usually we clean up also before and after the test - maybe we could adapt a convention that a wrapper flow should only clean up either before *or* after - e.g. a wrapper flow could clean up before the test (if it has to do something with images -> clear docker host, otherwise -> clear containers)

#266 also related

**Comment by tudorlesan** [comment]
agree with @Bonczidai. Basically if all the test flows clear the docker host both before they start and after they finish, this means that after the first test flow finishes, the second test flow clears the docker host once again which is redundant. Don't know how much time this saves up but it's worth a try. There is only one problem. When one of the test flows fail, they don't end up clearing the docker host so this means that the next test flow really should clean it before it starts. Maybe add a clear_docker_host on_failure?

**Comment by orius123** [comment]
Ok.
I think that we can make all tests to clean before (and that way even if earlier flow fails it doesn't matter), but regarding #266, I think we still have an issue, because if the host is clean, it should take no-time to run the clear-docker-host flow. (and it doesn't..)
