### ISSUE TITLE
SSH return code doesn't return expected exit code

### ISSUE THREAD

**Issue by orius123** [CloudSlang/cloud-slang-content#245]
by @lirantal 
>I changed the ```restart_service``` flow to use the return_code that the SSH command from the imported script exposes:
![image](https://cloud.githubusercontent.com/assets/316371/8599721/cab5fa44-266a-11e5-8e6e-7f75e9e3afaa.png)

Then I ran the flow with arguments that I know will make it fail:
![image](https://cloud.githubusercontent.com/assets/316371/8599770/062af890-266b-11e5-8b78-237b6bed9e5e.png)

As you can see return_code is 0 even though the flow failed.
Am I doing something wrong with the return_code usage in the flow or is that an actual defect?

**Comment by meirwah** [comment]
seems like an issue in the SSH action...

**Comment by meirwah** [comment]
@Alex-Persa can you take a look if this is an action issue?

**Comment by Alex-Persa** [comment]
Yes, the ssh operation was designed to return SUCCESS if it succeeds to connect to the server launch the command and recieve the result of the ssh invocation. Even if the results says that the command is invalid or failed to execute. You can see if succeeded from STDOUT and STDERR. 

This is the pice of code responsable for this behaviour.
![untitled0](https://cloud.githubusercontent.com/assets/9443830/8669762/e9280fcc-2a1f-11e5-8ff8-0c04c36931c7.png)
ExitCode meaning: http://support.attachmate.com/techdocs/2116.html


This is an example of an invalid command which will go to success because ssh successfuly sayed that the command is invalid.:
![untitled](https://cloud.githubusercontent.com/assets/9443830/8669770/f837f00e-2a1f-11e5-9a71-7a16c171f59d.png)

This behaviour can be easily changed if a functional architecht decide that this is not what we want anymore.

**Comment by meirwah** [comment]
Is this the same as in OO actions?

**Comment by Alex-Persa** [comment]
Yes

**Comment by meirwah** [comment]
first of all, why is the exit code not an action output? so the user can deiced later if to use it or not...

**Comment by Alex-Persa** [comment]
I've done little research.
In OO exitStatus is an action output.
![untitled0](https://cloud.githubusercontent.com/assets/9443830/8671898/95864e26-2a31-11e5-8990-10fed26c2ae7.png)

oo-base content don't use core-ssh code. The implementation is similar. Maybe @ioanvranau knows more about the reasons behind this since he created score-ssh. From what I remeber there was some limitation on SessionObject.

We should add exitStatus as an action result in score-ssh too.

**Comment by meirwah** [comment]
yes.. please add an issue on that for that on the score-actions repo...
@ioanvranau can you share your POV on this?

**Comment by ioanvranau** [comment]
There are no reasons about that. Most probably nobody needed this output until now as this code is written for cloudslang flows. There are no problems to add a new output to an operation if you need it for developing ootb content flows. Adding inputs just by "coziness" it is not a good practice, but I think this is not the case.

**Comment by lirantal** [comment]
Thanks guys for this great fix!
