### ISSUE TITLE
Test also Docker 1.8

### ISSUE THREAD

**Issue by orius123** [CloudSlang/cloud-slang-content#297]
Add to our matrix different versions of docker.

**Comment by tethryus** [comment]
Tests are running on 1.8 hence the need to test, due to the implementation method, if it will ever change, there will be an impact over the whole CI build part. We are using Docker 1.8 when a new PR is opened or any other builds. On top of that the testing different versions of Docker will work, since the commands haven`t changed (the ones that we have implemented) throughout different versions. This issue can be closed.
