### ISSUE TITLE
demo_dev_ops and ping_hosts not working

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang-content#298]
Is this correct @tudorlesan ? can you update on what you tested ? and what issues did you find?

**Comment by orius123** [comment]
demo devops works for me after manually starting a postfix server

**Comment by orius123** [comment]
also ping host.
maybe you had problem with postfix?

**Comment by tudorlesan** [comment]
The thing is, I manually ran these flows. So no tests, and no postfix. I used an HP smtp server which worked a while back. As I said, demo dev ops might not be working because the machine I have access to does not have enough ram and cannot start the mysql container, though I find it odd that the flow does not fail. While ping hosts just says all hosts are down.

**Comment by Bonczidai** [comment]
if you are using an 512 MB droplet on DO you can define swap space following this article: https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04 (also works for CoreOS)

**Comment by tudorlesan** [comment]
I tested the ping_hosts flow and it works. It was just a problem on what network I was connected on. Thanks @Bonczidai. Creating a swap file helped in running the mysql container for the demo_dev_ops flow. Now there is just one thing that I don't get. Though both containers get started and I can access the app from my browser, the test_application step of the flow times out.

**Comment by orius123** [comment]
No idea.. :godmode:

**Comment by meirwah** [comment]
Adding @gituser173

**Comment by tudorlesan** [comment]
:+1:
