### ISSUE TITLE
Math comparisons ops [5]

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang-content#357]

**Comment by oritstone** [comment]
- Is Equal
- Not Equal
- Greater Than
- Greater Than or Equal
- Less Than
- Less Than or Equal

**Comment by SamMarkowitz** [comment]
What kind of results do we expect from these? 

1. `TRUE` and `FALSE` as you would get in a programming language 
2. Or something like `EQUALS` and `NOT_EQUALS`. 

If option 2, doesn't it make sense to have fewer operations. For example it would be strange to have both an `equals` and `not equals` operation that would both result in either `EQUALS` or `NOT_EQUALS`?

@oritstone, @Bonczidai

**Comment by Bonczidai** [comment]
I would go with the second approach similar to what we have in DO content -> [compare_float](https://github.com/CloudSlang/cloud-slang-content/blob/9ada768d6a5af3abaabf0a831adb26540106e439/content/io/cloudslang/base/math/comparisons/compare_float.sl) - maybe enhance it and add an `equals` op -- I don't like adding lots of operations like <, <=, >, >= since we easily encapsulate these checks in task navigation section and the additional computing effort in worst case is 1 check in the result condition:

```
  navigate:
    GREATER_THAN: >
    EQUALS:  ==
    LESS_THAN: <
```

lets hear what others think - adding @mihaitusa
