### ISSUE TITLE
XML processing

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang-content#360]

**Comment by SamMarkowitz** [comment]
@mihaitusa - is there a list of the functionality we want?

**Comment by Bonczidai** [comment]
IMHO it includes validation, CRUD on elements and attributes (parse the xml tree)

**Comment by Bonczidai** [comment]
adding @gituser173

**Comment by SamMarkowitz** [comment]
There is no module in the standard Python library that fully supports XPath. Therefore we're going to use an external package, lxml, for this content. 

Comments, suggestions, and or disagreements regarding this decision are welcome (the sooner the better obviously).

**Comment by SamMarkowitz** [comment]
I'm stuck on which XML parser to use. Here's the story:

The fastest and most fully featured of the XML processing modules in the Python standard library is ElementTree. However, XPath support seems to be a requirement for whatever parser we use, and ElementTree only supports a [limited subset](https://docs.python.org/2/library/xml.etree.elementtree.html#supported-xpath-syntax) of XPath.

So, I looked into external packages, of which lxml is the most popular and fully featured of the bunch. However, it (and seemingly the other external packages that support XPath) don't install well with pip (certainly not on Windows), which is how we recommend using external modules and how we install CI machines, due to C stuff. There is one external package that claims to do XPath in pure Python (avoiding install issues) but it has no documentation, is v0.1, and it's GitHub repo hasn't been touched in 5 years.

Here's a bit of an [overview of the situation](https://wiki.python.org/moin/PythonXml).  

I'm probably missing something here. Ideas?

@gituser173, @mihaitusa, @Bonczidai, @meshipeer

**Comment by SamMarkowitz** [comment]
Third party libraries don't work with Jython. Moving to @actions instead.
