### ISSUE TITLE
CircleCI on master not stable [2]

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang-content#364]
https://circleci.com/gh/CloudSlang/cloud-slang-content/tree/master

**Comment by meirwah** [comment]
@gituser173 CircleCI seems unstable.. on many PR, please look into this...

**Comment by meirwah** [comment]
https://circleci.com/gh/CloudSlang/cloud-slang-content/1911

**Comment by gituser173** [comment]
https://circleci.com/gh/CloudSlang/cloud-slang-content/1911
Looks like the "com.jcraft.jsch.JSchException: session is down" exception is found in this log. Maybe the code that fixes this issue is not on this branch? This was fixed in master.

**Comment by Bonczidai** [comment]
you can merge from master into that branch, push it and see if it is reproduced

**Comment by gituser173** [comment]
Most of the errors from the master https://circleci.com/gh/CloudSlang/cloud-slang-content/tree/master are related to https://github.com/CloudSlang/score-actions/issues/74 which is fixed by @Bonczidai in https://github.com/CloudSlang/score-actions/pull/79. Also there are some exceptions that might be caused by network errors. Also merged from master for https://circleci.com/gh/CloudSlang/cloud-slang-content/1911 and the "session is down" is still there. I will continue investigating
