### ISSUE TITLE
customize_windows_guest fails when computer_password is given empty

### ISSUE THREAD

**Issue by dumagalex** [CloudSlang/cloud-slang-content#597]
Supposing  a user would try to remove the computerPassword by running customize_windows_guest.sl with computer_password: "", he will fail with the error below:

"returnResult=com.sun.xml.internal.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: 
Required property value is missing from data object of type CustomizationPassword"

**Comment by dumagalex** [comment]
This is less of an issue for Studio content where administratorPassword is not a required input so leaving it empty would simply mean the user doesn't want to change the existing password

**Comment by mihaitusa** [comment]
@dumagalex Since the "computer_password" is a required input and has a supplementary validation against the empty string I don't know if is a problem if the user don't provide anything in here. The error itself is a VMware validation error. Because I use different library than in content it can occur cases when the behavior is slightly different. Conclusion: I think if VMware specs validation throw this error than we should do to...

**Comment by dumagalex** [comment]
@mihaitusa Agreed. However, I would like us to enhance the description for "computer_password" to say that you can't remove the guest password by setting this input to ""

**Comment by mihaitusa** [comment]
@dumagalex I Agree with you. I will modify the description accordingly.

**Comment by mihaitusa** [comment]
Modified the computer_password input description to state clearly that empty string is not valid input.

**Comment by mihaitusa** [comment]
Fixed in  Expand-the-VMware-Integration #561

**Comment by mihaitusa** [comment]
@dumagalex Still wait for confirmation on this one.

**Comment by dumagalex** [comment]
Confirming the description now covers this case and the operation can still run successfully
